# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: big_data_optimizer_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env       # make sure this file exists
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --workers 4
      --forwarded-allow-ips="*"
      --proxy-headers
    volumes:
      - ${UPLOAD_DIR}:/app/backend/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: big_data_optimizer_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env.local      # optional, if you have env vars for API URL
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: npm run start